#!/bin/bash

# OneDrive Sync Change Report Generator
# Compares local state with OneDrive backup to show what changed

set -e

TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
HOSTNAME=$(hostname)
REPORT_FILE="$HOME/logs/sync-report-$TIMESTAMP.md"
SNAPSHOT_DIR="$HOME/.cloud-sync-snapshots"
PREV_SNAPSHOT="$SNAPSHOT_DIR/last-sync.txt"
CURR_SNAPSHOT="$SNAPSHOT_DIR/current-sync-$TIMESTAMP.txt"

mkdir -p "$HOME/logs"
mkdir -p "$SNAPSHOT_DIR"

echo "# OneDrive Sync Change Report" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "**Date:** $(date)" >> "$REPORT_FILE"
echo "**Host:** $HOSTNAME" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Generate current snapshot
echo "📸 Creating snapshot of OneDrive state..."
rclone lsl "onedrive:DevEnvironment/$HOSTNAME/essentials/" --max-depth 10 2>/dev/null | \
    awk '{print $4, $1, $2, $3}' | sort > "$CURR_SNAPSHOT"

# Compare with previous snapshot if it exists
if [ -f "$PREV_SNAPSHOT" ]; then
    echo "" >> "$REPORT_FILE"
    echo "## 🔄 Changes Since Last Sync" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    
    # Find new files
    NEW_FILES=$(comm -13 "$PREV_SNAPSHOT" "$CURR_SNAPSHOT" | wc -l)
    MODIFIED_FILES=$(comm -12 <(cut -d' ' -f1 "$PREV_SNAPSHOT" | sort) <(cut -d' ' -f1 "$CURR_SNAPSHOT" | sort) | wc -l)
    DELETED_FILES=$(comm -23 "$PREV_SNAPSHOT" "$CURR_SNAPSHOT" | wc -l)
    
    echo "**Summary:**" >> "$REPORT_FILE"
    echo "- 🆕 New files: $NEW_FILES" >> "$REPORT_FILE"
    echo "- 📝 Potential modifications: $MODIFIED_FILES" >> "$REPORT_FILE"
    echo "- 🗑️  Deleted files: $DELETED_FILES" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    
    # List new files
    if [ "$NEW_FILES" -gt 0 ]; then
        echo "### 🆕 New Files Added" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
        comm -13 "$PREV_SNAPSHOT" "$CURR_SNAPSHOT" | head -50 >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    fi
    
    # List deleted files
    if [ "$DELETED_FILES" -gt 0 ]; then
        echo "### 🗑️  Files Deleted" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
        comm -23 "$PREV_SNAPSHOT" "$CURR_SNAPSHOT" | head -50 >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    fi
else
    echo "## ℹ️  First Sync Report" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "This is the first sync report. Future syncs will show diffs." >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# Current statistics
echo "## 📊 Current Backup Statistics" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for dir in "docs" "scripts" "mcp-servers" ".ssh" "templates"; do
    if rclone lsd "onedrive:DevEnvironment/$HOSTNAME/essentials/$dir" &>/dev/null; then
        size_info=$(rclone size "onedrive:DevEnvironment/$HOSTNAME/essentials/$dir" 2>&1 | grep "Total")
        objects=$(echo "$size_info" | grep "objects" | awk '{print $3}')
        size=$(echo "$size_info" | grep "size" | awk '{print $3, $4}')
        echo "- **$dir**: $objects files, $size" >> "$REPORT_FILE"
    fi
done

echo "" >> "$REPORT_FILE"
echo "## 📁 Directory Structure (depth 2)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "\`\`\`" >> "$REPORT_FILE"
rclone tree "onedrive:DevEnvironment/$HOSTNAME/essentials/" --max-depth 2 2>&1 >> "$REPORT_FILE"
echo "\`\`\`" >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by CloudSync system at $TIMESTAMP*" >> "$REPORT_FILE"

# Save current snapshot as "last sync"
cp "$CURR_SNAPSHOT" "$PREV_SNAPSHOT"

echo "✅ Report saved to: $REPORT_FILE"
echo ""
echo "📄 Report preview:"
head -50 "$REPORT_FILE"
